# DataSource (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skill_tech?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

# Hibernate

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace