server:
  address: localhost
  port: 8080

# DataSource (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skill_tech?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

# Thymeleaf
  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

# Hibernate
# The SQL dialect makes Hibernate generate better SQL for the chosen database
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
